FishingAdventure:
  Message:
    Prefix: "&fTEST"
  RankPrefix:
    C: "&8[ &7C &8]"
    B: "&f[ &bB &f]"
    A: "&f[ &eA &f]"
    S: "&f[ &aS &f]"
  RankPercent:
    0:
      C: 60
      B: 20
      A: 15
      S: 5
    1:
      C: 60
      B: 20
      A: 15
      S: 5
    2:
      C: 60
      B: 20
      A: 15
      S: 5
    3:
      C: 60
      B: 20
      A: 15
      S: 5