main: com.goldfrosch.plugin.MainPlugin
name: FishingAdventure
version: 1.0.2
api-version: 1.16
author: GoldFrosch
commands:
  fishing:
    description: Main Command of FishingAdventure!

permissions:
  fishingAdventure.op:
    default: op